[browser]
gatherUsageStats = false

[theme]
primaryColor="#FF913A"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#262730"
font="sans serif"

[logger]
level = "error"

[client]
toolbarMode = "auto"