[[pages]]
path = "main.py"
name = "General Overview"
icon = "ğŸ "

[[pages]]
path = "pages/dataset_explorer.py"
name = "Dataset Explorer"
icon = "ğŸ“Š"

[[pages]]
path = "pages/global_value_search.py"
name = "Global Value Search"
icon = "ğŸ”"

[[pages]]
path = "pages/compare_runs.py"
name = "Compare Runs"
icon = "ğŸ”"

[[pages]]
path = "pages/image_gallery.py"
name = "Image Gallery"
icon = "ğŸ–¼ï¸"

[[pages]]
path = "pages/numeric_analysis.py"
name = "Numerical Analysis"
icon = "ğŸ“ˆ"