[[pages]]
path = "main.py"
name = "General Overview"
icon = "ğŸ "

[[pages]]
path = "pages/dataset.py"
name = "Dataset Explorer"
icon = "ğŸ“Š"


[[pages]]
path = "pages/images.py"
name = "Image Gallery"
icon = "ğŸ–¼ï¸"

[[pages]]
path = "pages/statistics.py"
name = "Numerical Analysis"
icon = "ğŸ“ˆ"